import Head from 'next/head'
import Image from "next/image"
import styles from '../styles/Home.module.css'

import Card from '../components/Card'

export async function getStaticProps(){

  const maxPokemons = 251
  const api = "https://pokeapi.co/api/v2/pokemon/"
  
  const res = await fetch(`${api}/?limit=${maxPokemons}`)
  const data = await res.json()

  // add pokemon index
  data.results.forEach((item, index) => {
    item.id = index + 1
  })

  return {
    props: {
      pokemons: data.results
    }
  }

}

export default function Home({pokemons}) {

  return (
    <>
      <Head>
        <title>PokeNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <div className={styles.title_container}>
        <h1>Poke<span>Next</span></h1>
        <Image 
          src="/images/pokeball.png"
          width="50"
          height="50"
          alt="PodeNext"
        />
      </div>
      <div className={styles.pokemon_container}>
        {pokemons.map(pokemon => (
          <Card 
            key={pokemon.id}
            pokemon={pokemon}
          />
        ))}
      </div>
    </>
  )
}
